version: '3.8'
services:
  prototype-upd8-laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./laravel-api:/var/www:cached
    depends_on:
      - dbrepzone
    networks:
      - personwallet-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      DB_HOST: dbrepzone
      DB_PORT: 3306
      DB_DATABASE: repzone
      DB_USERNAME: repzone
      DB_PASSWORD: repzone

  dbrepzone:
    image: mysql:8.0
    container_name: dbrepzone
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: repzone
      MYSQL_USER: repzone
      MYSQL_PASSWORD: repzone
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - personwallet-network

networks:
  personwallet-network:
    external: true

volumes:
  mysql_data:
