services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    autoDeploy: true
    dockerContext: .
    dockerfilePath: Dockerfile.prod
    buildCommand: ""
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0qocpruibrs73epndtg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: repzone
      - key: DB_USERNAME
        value: repzone
      - key: DB_PASSWORD
        sync: false
